### ISSUE TITLE
Misspelt CMake option: "CUDA_SEPERABLE_COMPILATION"

### ISSUE THREAD

**Issue by anibali** [Sibras/FFFrameReader#7]
https://github.com/Sibras/FFFrameReader/blob/245f531e9069b65128ae5b0fdcdfebac80e58566/CMakeLists.txt#L100

Should be `CUDA_SEPARABLE_COMPILATION`, see https://cmake.org/cmake/help/latest/prop_tgt/CUDA_SEPARABLE_COMPILATION.html.

**Comment by Sibras** [comment]
I actually cut &pasted that line so clearly i got it from the wrong source
